// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CacheDAL is an autogenerated mock type for the CacheDAL type
type CacheDAL struct {
	mock.Mock
}

// GetToken provides a mock function with given fields: token
func (_m *CacheDAL) GetToken(token string) (string, error) {
	ret := _m.Called(token)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetUserToken provides a mock function with given fields: userID, token
func (_m *CacheDAL) SetUserToken(userID string, token string) error {
	ret := _m.Called(userID, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
